#!/bin/bash

# Abort script at first error, follow the fail fast principle (https://en.wikipedia.org/wiki/Fail-fast)
set -e

# --- SETUP AND GLOBAL FUNCTIONS --- #
# Program logic isn't evaluated yet.

# The directory of the script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Set by the -d or -p flag
MODE=""

source "${DIR}/common"

# Always call the error function on the ERR signal, this is used in conjuntion with set -e and gives us some
# extra debugging information
trap 'on_error ${LINENO}' ERR

show_help() {
    echo "
Help and Usage
-------------------------------------------------------------
-h, --help                      Show this help window
-d, --dev                       Run in developer mode
-p, --prod                      Run in production mode
"
}

parse_command_options() {
    while [[ $# -gt 0 ]]
    do
    key="$1"

    case $key in
        -h|--help)
        show_help
        exit
        ;;
        -d|--dev)
        MODE="dev"
        ;;
        -p|--p)
        MODE="prod"
        ;;
        *)
            # unknown option
        ;;
    esac
    shift # past argument or value
    done
}

# --- END SETUP AND GLOBAL FUNCTIONS --- #

# --- SCRIPT LOGIC --- #
# The program actually begins here, and mostly just calls the functions defined above

parse_command_options $@

echo "${BANNER}"

echo -e "Purpose: Runs the docker image in dev or production mode\n\n"

$DIR/build-presentation

echo -e "\n --- \n"

echo_inf "Step 1. Checking for prerequisite commands"
assert_command_exists docker "To install Docker on your system, go to https://docs.docker.com/engine/installation/"
assert_command_exists wc "wc is used in this script to measure line count"
assert_command_exists realpath "realpath is used to determine a path to a resource"

echo_inf "Step 2. Asserting script was called correctly"

# Assert that MODE was set, we need to know if this is a development or production environment to set up
# options for docker run
if [ "${MODE}" == "" ]; then
    echo_err "mode must be set"
    show_help
    exit 1
fi
echo_inf "  ${GREEN}✓${RESTORE} MODE variable set"

echo_inf "Step 3. Checking for image ${PRESENTATION_IMAGE_NAME}:${PRESENTATION_IMAGE_TAG}"

# Uses docker images to check for the heweb image, if it doesn't exist the wc command will return 
IMAGE_EXISTS=$(docker images "${PRESENTATION_IMAGE_NAME}:${PRESENTATION_IMAGE_TAG}" --format "{{.ID}}" | wc -l)
if [ "${IMAGE_EXISTS}" == "0" ]; then
    echo_err "  ${RED}!${RESTORE} Could not find image, run build script first"
    exit 1
fi
echo_inf "  ${GREEN}✓${RESTORE} image found"

DOCKER_OPTS="run -i --name ${PRESENTATION_CONTAINER_NAME} --rm -p ${PRESENTATION_CONTAINER_EXTERNAL_PORT}:80" 
if [ "${MODE}" == "dev" ]; then
    WWW_SRC_DIR=$(realpath "${DIR}/../sites/presentation")
    DOCKER_OPTS="${DOCKER_OPTS}  -v ${WWW_SRC_DIR}:/usr/share/nginx/html"    
fi
DOCKER_OPTS="${DOCKER_OPTS} -t ${PRESENTATION_IMAGE_NAME}:${PRESENTATION_IMAGE_TAG}"

echo_inf "Step 4. Starting ${CYAN}${MODE}${RESTORE} image with options ${CYAN}${DOCKER_OPTS}${RESTORE}"
if [ "${MODE}" == "dev" ]; then
    # WWW_SRC_DIR is defined in the previous if statement
    echo_wrn "  ${YELLOW}⚠${RESTORE} dev mode mounts src directory at ${CYAN}${WWW_SRC_DIR}${RESTORE}, this overlays any content in the image"
fi

echo ""
echo_inf "You can exit this script by pressing CONTROL-C\n\n"
docker $DOCKER_OPTS 